Repository knex/knex, pull requests merged in 2018-11, with the labels that each got.

#2719 Add option of existingType to .enum method to support repeated use of enums
  src/dialects/postgres/schema/columncompiler.js
  test/integration/schema/index.js
  test/unit/schema/postgres.js
Labels: missing documentation, missing tests

#2873 Execute tests on Node.js 11
  .travis.yml
  package.json
Labels: external issue filed

#2890 Added option to pass indexType for MySQL dialect
  src/dialects/mysql/schema/tablecompiler.js
  test/unit/schema/mysql.js
Labels: ready

#2861 Support patched MSSQL lib
  package.json
  src/dialects/mssql/index.js
Labels: external issue filed
