Repository knex/knex, pull requests merged in 2020-12, with the labels that each got.

#4122 Drop liftoff
  UPGRADING.md
  bin/cli.js
  bin/utils/cli-config-utils.js
  lib/util/fs.js
  package.json
Labels: breaking change, ready

#3702 whatwg url connection string parsing
  lib/util/parse-connection.js
  test/tape/parse-connection.js
Labels: breaking change

#4185 Add transaction isolation support
  lib/dialects/mssql/transaction.js
  lib/dialects/oracledb/transaction.js
  lib/dialects/postgres/index.js
  lib/dialects/postgres/transaction.js
  lib/dialects/redshift/transaction.js
  lib/dialects/sqlite3/index.js
  lib/dialects/sqlite3/transaction.js
  lib/execution/transaction.js
  lib/knex-builder/make-knex.js
  scripts/docker-compose.yml
  test/integration2/transaction/set-isolation-level.spec.js
  test/util/db-helpers.js
  types/index.d.ts
Labels: missing documentation

#4186 fallback to json for sqlite3 when using jsonb
  lib/dialects/sqlite3/schema/columncompiler.js
  test/integration2/schema/jsonb.spec.js
Labels: missing tests
