Repository knex/knex, pull requests merged in 2021-02, with the labels that each got.

#4266 Primary keys improvements
  lib/dialects/mssql/schema/mssql-columncompiler.js
  lib/dialects/mysql/schema/mysql-columncompiler.js
  lib/dialects/mysql/schema/mysql-tablecompiler.js
  lib/dialects/oracle/schema/oracle-columncompiler.js
  lib/dialects/postgres/schema/pg-columncompiler.js
  lib/dialects/redshift/schema/redshift-columncompiler.js
  lib/schema/columncompiler.js
  test/integration/query/trigger-inserts.js
  test/integration/schema/index.js
  test/unit/schema-builder/mssql.js
  test/unit/schema-builder/mysql.js
  test/unit/schema-builder/oracle.js
  test/unit/schema-builder/oracledb.js
  test/unit/schema-builder/postgres.js
  test/unit/schema-builder/sqlite3.js
Labels: missing documentation, missing tests, needs changes

#4268 Fix issue with schema usage with FROM clause
  lib/query/querycompiler.js
  test/unit/query/builder.js
Labels: needs rebasing

#2857 WIP: Replace MSSQL dialect with Tedious.js implementation
  lib/dialects/mssql/index.js
  lib/dialects/mssql/query/mssql-querycompiler.js
  lib/dialects/mssql/transaction.js
  package.json
  test/integration/execution/transaction.js
  test/integration/query/additional.js
  test/integration/query/selects.js
  test/unit/query/builder.js
Labels: MSSQL, high priority, improvement

#4283 MSSQL hotfix for error handling in cloud
  lib/dialects/mssql/transaction.js
Labels: MSSQL

#4252 Added merge strategy to allow selecting columns to upsert.
  lib/dialects/mysql/query/mysql-querycompiler.js
  lib/dialects/postgres/query/pg-querycompiler.js
  lib/dialects/sqlite3/query/sqlite-querycompiler.js
  package.json
  test-tsd/types.test-d.ts
  test/integration/query/inserts.js
  types/index.d.ts
Labels: missing documentation

#4319 mssql: schema builder - add predictable constraint names for default values
  lib/dialects/mssql/schema/mssql-columncompiler.js
  test/integration/schema/index.js
  test/integration2/dialects/mssql.js
  test/unit/schema-builder/mssql.js
  types/index.d.ts
Labels: MSSQL, missing documentation

#4321 mssql: schema builder - attempt to drop default constraints when changing default value on columns
  lib/dialects/mssql/schema/mssql-columncompiler.js
  lib/dialects/mssql/schema/mssql-tablecompiler.js
  test/integration2/dialects/mssql.js
  test/unit/schema-builder/mssql.js
Labels: missing tests
