Repository knex/knex, pull requests merged in 2021-03, with the labels that each got.

#4330 SQLite: made the constraint detection case-insensitive
  lib/dialects/sqlite3/schema/ddl.js
  test/integration2/schema/foreign-keys.spec.js
Labels: missing tests

#4358 Move QueryBuilder and KnexTimeoutError into knex namespace so that they are accessible at a runtime
  lib/knex-builder/Knex.js
  test-tsd/querybuilder.test-d.ts
  test-tsd/types.test-d.ts
  types/index.d.ts
Labels: typings

#4376 Rework dropForeign to use new tokenized structure
  lib/dialects/sqlite3/schema/ddl.js
Labels: SQLite, bug

#4324 Fix timeout method
  lib/dialects/mysql/index.js
  lib/dialects/postgres/index.js
  test/integration/query/additional.js
Labels: high priority, improvement

#4361 [wip] fixes #4335: warn if negative offset was provided
  lib/query/querybuilder.js
  test/integration/query/selects.js
Labels: missing tests
