Repository knex/knex, pull requests merged in 2021-01, with the labels that each got.

#4058 Make toSQL().toNative() work for Raw to match the API for QueryBuilder
  lib/raw.js
  test/tape/raw.js
Labels: missing tests

#4194 Return complete list of DDL commands for creating foreign keys in SQLite
  lib/dialects/sqlite3/schema/ddl.js
  lib/dialects/sqlite3/schema/internal/sqlite-ddl-operations.js
  lib/dialects/sqlite3/schema/sqlite-compiler.js
  lib/dialects/sqlite3/schema/sqlite-tablecompiler.js
  lib/execution/runner.js
  lib/schema/builder.js
  lib/schema/compiler.js
  lib/util/nanoid.js
  test/integration2/schema/foreign-keys.spec.js
  types/index.d.ts
Labels: SQLite, schema

#4172 Fix type definition of Transaction
  test-tsd/select.test-d.ts
  types/index.d.ts
  types/test.ts
Labels: discussion, typings

#3569 Allow 'match' operator
  lib/formatter/wrappingFormatter.js
  test/integration2/query/select/fts.spec.js
Labels: good first issue, missing tests

#3658 Add check to only create native enum once
  lib/dialects/postgres/schema/pg-tablecompiler.js
  lib/schema/columncompiler.js
  test/integration2/schema/enum-native.spec.js
  test/unit/schema-builder/postgres.js
Labels: PostgreSQL, missing tests

#4243 Allow optimizer hints
  lib/dialects/mssql/query/mssql-querycompiler.js
  lib/query/querybuilder.js
  lib/query/querycompiler.js
  test/integration/query/selects.js
  test/unit/query/builder.js
  types/index.d.ts
Labels: feature request, missing documentation
